### ISSUE TITLE
Reviewing the source code of the Python implementation 

### ISSUE THREAD

**Issue by sisgandarli** [aznlp/azerbaijani-language-stemmer#1]
Hi there. I have just finished writing the Python implementation of the word stemmer for Azerbaijani language according to the guidelines provided by Zamir bey [@Zamir10].

Please, review it [the code] and share your feedback at your earliest convenience.

**Comment by smr3mdv** [comment]
@Zamir10 Salam Zamir. Bu sözlərin siyahısı "words.txt" nəyə əsasən Obastanın lügətindən uzundur? Hər halda bizə söz birləşmələri lazım deyil stemming üçün. Məsələn, siyahıda "ilhamla" sözü var, hansı ki, nə Obastanın lüğətində var, nə də mən Azərbaycan dilində belə bir söz olduğunu düşünürəm.
