### ISSUE TITLE
Fix the order of suffixes in suffix.txt

### ISSUE THREAD

**Issue by ziyaddin** [aznlp/azerbaijani-language-stemmer#20]
acaq, əcək should come before aq, ək, because in example below:

etməyəcək: script removes ək instead of əcək and it becomes an invalid stem, as ək comes before əcək in the list.

**Comment by ziyaddin** [comment]
Now I put acaq, əcək before aq, ək in the suffix.txt. I will push the changes in new PR.

**Comment by smr3mdv** [comment]
Don't make elephant out of an ant. Just push.

**Comment by ziyaddin** [comment]
Already pushed. Vaxtında bax.
