### ISSUE TITLE
Does not work in case of participles and linking verb

### ISSUE THREAD

**Issue by mammadhajili** [aznlp/azerbaijani-language-stemmer#22]
Please consider those cases as well:
- oxuyan uşaqlar -> must return stem - "oxu", but returns "oxuyan"
- gedərkən gördü -> must return stem - "get", but returns "gedərkən"

**Comment by sisgandarli** [comment]
Thank you, Mammad ( @mammadhajili ), for contributing! 
Ziyaddin ( @ziyaddin ) and Samir ( @smr3mdv ) let's consider these cases, too.

**Comment by smr3mdv** [comment]
1) For some reason, some participles including "oxuyan" are on the list of words and must be removed.
2) Suffix forms (-kən) of conjunctives (ikən) must be added to the list of suffixes.

**Comment by mammadhajili** [comment]
@smr3mdv , appropriate suffix must be "arkən(ərkən)" for the second case. For preventing further issues related to participles and linking verbs, I recommend you add all suffixes, not only "an(ən)" or "arkən(ərkən)".

**Comment by smr3mdv** [comment]
@mammadhajili "-arkən(-ərkən)"="-ar(-ər)"+"ikən". This is not the only case suffix form of "ikən" is preceded by an inflectional suffix ("-mış^4"+"ikən"). If your advice is followed, all possible combinations of suffixes will need to be generated and added.
